import { renderSessionToHtml } from "../packages/render/src/renderer.js";
import type { ReviewSession } from "../packages/types/src/history.js";
import { writeFileSync } from "node:fs";

const session: ReviewSession = {
  id: "demo-ecl-001",
  timestamp: "2026-05-17T16:30:00.000Z",
  trigger: "hook",
  summary: "WASM testing strategy: export internals + rewrite tests",
  total_changes: 5,
  files_changed: [
    "packages/ast/src/ts-parser.ts",
    "packages/ast/src/parser.ts",
    "packages/hook/src/index.ts",
  ],
  changes: [
    {
      id: "c1",
      timestamp: "2026-05-17T16:30:01.000Z",
      file_path: "packages/ast/src/ts-parser.ts",
      function_hash: "a1b2c3d4e5f60001",
      function_name: "extractTsFunction",
      class_name: null,
      change_type: "modify",
      reason: "Export internal functions for direct testing without WASM",
      reason_source: "context",
      old_content: "function extractTsFunction(node: SyntaxNode): FunctionSignature {",
      new_content: "/** @internal */\nexport function extractTsFunction(node: SyntaxNode): FunctionSignature {",
      start_line: 45,
      end_line: 72,
      test_status: "pass",
      test_file: ".devcompanion/tests/ts-parser-internal.test.ts",
      error_id: null,
      session_id: "demo-ecl-001",
      ecl_context: {
        feature: "wasm-testing-strategy",
        requirements: ["REQ-001", "REQ-002"],
        decisions: ["DEC-002"],
        ecl_file: "docs/ecl/wasm-testing-strategy.yaml",
      },
    },
    {
      id: "c2",
      timestamp: "2026-05-17T16:30:02.000Z",
      file_path: "packages/ast/src/ts-parser.ts",
      function_hash: "a1b2c3d4e5f60002",
      function_name: "extractTsClass",
      class_name: null,
      change_type: "modify",
      reason: "Export internal functions for direct testing without WASM",
      reason_source: "context",
      old_content: "function extractTsClass(node: SyntaxNode): ClassInfo {",
      new_content: "/** @internal */\nexport function extractTsClass(node: SyntaxNode): ClassInfo {",
      start_line: 80,
      end_line: 115,
      test_status: "pass",
      test_file: ".devcompanion/tests/ts-parser-internal.test.ts",
      error_id: null,
      session_id: "demo-ecl-001",
      ecl_context: {
        feature: "wasm-testing-strategy",
        requirements: ["REQ-001"],
        decisions: ["DEC-002"],
        ecl_file: "docs/ecl/wasm-testing-strategy.yaml",
      },
    },
    {
      id: "c3",
      timestamp: "2026-05-17T16:30:03.000Z",
      file_path: "packages/ast/src/parser.ts",
      function_hash: "a1b2c3d4e5f60003",
      function_name: "initPythonParser",
      class_name: null,
      change_type: "modify",
      reason: "Delegate WASM path resolution to wasm-resolver.ts",
      reason_source: "context",
      old_content: "const wasmPath = resolve(__dirname, '../../../node_modules/tree-sitter-python/tree-sitter-python.wasm');",
      new_content: "const wasmPath = resolveWasmPath('tree-sitter-python', 'tree-sitter-python.wasm');",
      start_line: 12,
      end_line: 35,
      test_status: "pass",
      test_file: ".devcompanion/tests/test_ast_findWasmPath.test.ts",
      error_id: null,
      session_id: "demo-ecl-001",
      ecl_context: {
        feature: "wasm-testing-strategy",
        requirements: ["REQ-002"],
        decisions: ["DEC-001"],
        ecl_file: "docs/ecl/wasm-testing-strategy.yaml",
      },
    },
    {
      id: "c4",
      timestamp: "2026-05-17T16:30:04.000Z",
      file_path: "packages/hook/src/index.ts",
      function_hash: "a1b2c3d4e5f60004",
      function_name: "detectActiveEcl",
      class_name: null,
      change_type: "add",
      reason: "Auto-detect active ECL for change context enrichment",
      reason_source: "context",
      old_content: null,
      new_content: "function detectActiveEcl(projectRoot: string): EclContextSlim | undefined {\n  const eclDir = join(projectRoot, 'docs', 'ecl');\n  // ... scans yaml files\n}",
      start_line: 77,
      end_line: 109,
      test_status: "pending",
      test_file: null,
      error_id: null,
      session_id: "demo-ecl-001",
      ecl_context: {
        feature: "ecl-context-linking",
        decisions: ["DEC-001"],
        ecl_file: "docs/ecl/ecl-context-linking.yaml",
      },
    },
    {
      id: "c5",
      timestamp: "2026-05-17T16:30:05.000Z",
      file_path: "packages/hook/src/index.ts",
      function_hash: "a1b2c3d4e5f60005",
      function_name: "handlePostToolUse",
      class_name: null,
      change_type: "modify",
      reason: "Attach ECL context to hook events",
      reason_source: "context",
      old_content: "    reason: \"auto-captured from Claude Code session\",\n  };",
      new_content: "    reason: \"auto-captured from Claude Code session\",\n    ecl_context: detectActiveEcl(projectRoot),\n  };",
      start_line: 23,
      end_line: 62,
      test_status: "pass",
      test_file: ".devcompanion/tests/test_hook_handlePostToolUse.test.ts",
      error_id: null,
      session_id: "demo-ecl-001",
      ecl_context: {
        feature: "ecl-context-linking",
        requirements: ["REQ-001"],
        decisions: ["DEC-001"],
        ecl_file: "docs/ecl/ecl-context-linking.yaml",
      },
    },
  ],
};

const html = renderSessionToHtml(session, []);
writeFileSync("demo-ecl-report.html", html);
console.log("Written: demo-ecl-report.html");
